Models/ErrorViewModel.cs
using System;

namespace NetMoodtapeSpotifyClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PlaylistListItemModel.cs
using System.ComponentModel.DataAnnotations;

namespace NetMoodtapeSpotifyClient.Models
{
    public class PlaylistListItemModel
    {
        [Display(Name = "ID")]
        public string Id { get; set; }

        [Display(Name = "Name")]
        public string Name { get; set; }

        [Display(Name = "Owner")]
        public string Owner { get; set; }

        [Display(Name = "No. of tracks")]
        public int NumberOfTracks { get; set; }

        [Display(Name = "Is Public")]
        public bool? IsPublic { get; set; }

        [Display(Name = "Is Collaborative")]
        public bool IsCollaborative { get; set; }

        [Display(Name = "Is Owned")]
        public bool IsOwned { get; set; }
    }
}

Controllers/CallbackController.cs
using FluentSpotifyApi;
using Microsoft.AspNetCore.Mvc;

namespace NetMoodtapeSpotifyClient.Controllers
{
    public class CallbackController : Controller
    {
        public IFluentSpotifyClient _spotifyClient { get; set; }
        public CallbackController(IFluentSpotifyClient spotifyClient){
            _spotifyClient = spotifyClient;
        }
        public ActionResult Index(){
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using FluentSpotifyApi;
using FluentSpotifyApi.AuthorizationFlows.AspNetCore.AuthorizationCode.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetMoodtapeSpotifyClient.Models;

namespace NetMoodtapeSpotifyClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly IFluentSpotifyClient fluentSpotifyClient;

        public HomeController(IFluentSpotifyClient fluentSpotifyClient)
        {
            this.fluentSpotifyClient = fluentSpotifyClient;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [Route("/signin-spotify/")]
        public ActionResult SigninSpotify(){
            return RedirectToAction("Signin", "Authentication");
        }

        [Authorize]
        public async Task<IActionResult> Playlists()
        {
            var userId = this.User.GetNameIdentifier();

            var model = (await this.fluentSpotifyClient.Me.Playlists.GetAsync(limit: 20, offset: 0))
                .Items
                .Select(item => new PlaylistListItemModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    Owner = item.Owner?.DisplayName ?? item.Owner?.Id,
                    NumberOfTracks = (item.Tracks?.Total).GetValueOrDefault(),
                    IsPublic = item.Public,
                    IsCollaborative = item.Collaborative,
                    IsOwned = item.Owner?.Id == userId
                }).ToList();

            return this.View(model);
        }
    }
}

Controllers/MoodtapeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentSpotifyApi;
using FluentSpotifyApi.Builder.Me.Personalization.Top;
using FluentSpotifyApi.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetMoodtapeSpotifyClient.Service;

namespace NetMoodtapeSpotifyClient.Controllers
{
    public class MoodtapeController : Controller
    {
        private readonly IFluentSpotifyClient _spotifyClient;
        private readonly IUserService _userService;
        private readonly IArtistService _artistService;
        private readonly ITrackService _trackService;
        public MoodtapeController(IFluentSpotifyClient spotifyClient, 
                                    IUserService userService, IArtistService artistService,
                                    ITrackService trackService){
            _spotifyClient = spotifyClient;
            _userService = userService;
            _artistService = artistService;
            _trackService = trackService;
        }
        [Authorize]
        public ActionResult Index(){
            return View();
        }
        private float GetMood(int rating){
            float mood = 0;
            if(rating == 1)
                mood = 0.5f;
            if(rating == 2)
                mood = 0.1f;
            if(rating == 3)
                mood = 0.3f;
            if(rating == 4)
                mood = 0.6f;
            if(rating == 5)
                mood = 0.8f;
            if(rating == 6)
                mood = 1;
            return mood;
        }

        [Authorize]
        public async Task<ActionResult> Select(int rating){
            var mood = GetMood(rating);

            var topArtists = await _userService.GetTopArtistsFromUser();
            var topTracks = await GetTopTracks(topArtists);
            var tracksByMood = await _trackService.SelectTracksByMood(topTracks, mood);

            return View(tracksByMood);
        }
        private async Task<List<FullTrack>> GetTopTracks(List<FullArtist> topArtists){
            var topTracks = new List<FullTrack>();
            foreach(var artist in topArtists){
                var topTracksPerArtist = await _trackService.GetTopTracks(artist, "br");
                topTracks.AddRange(topTracksPerArtist);
            }
            return topTracks;
        }


    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Playlists.cshtml
@model IEnumerable<NetMoodtapeSpotifyClient.Models.PlaylistListItemModel>

<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owner)
        </th>
        <th class="text-right">
            @Html.DisplayNameFor(model => model.NumberOfTracks)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsCollaborative)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsOwned)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner)
            </td>
            <td class="text-right">
                @Html.DisplayFor(modelItem => item.NumberOfTracks)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPublic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCollaborative)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsOwned)
            </td>
        </tr>
    }

</table>

Views/Moodtape/Index.cshtml
<p>
    <h1>Select the mood:</h1><hr>
<div id="element"></div>
</p>

Views/Moodtape/Select.cshtml
@model IEnumerable<FluentSpotifyApi.Model.FullTrack>

<ul>
    @foreach(var item in Model){
        <li>
            @item.Artists.FirstOrDefault().Name - @item.Name
        </li>
    }
    
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCore SpotifyClient</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">NetCore SpotifyClient</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                    <li><a asp-area="" asp-controller="Moodtape" asp-action="Index">Moodtape</a></li>
                    <li><a asp-area="" asp-controller="Logout" asp-action="Index">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - NetMoodtapeSpotifyClient</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/emotion-ratings.js"></script>
        <script>
var emotionsArray = ['disappointed','meh', 'happy','smile', 'laughing','inlove'];
  $("#element").emotionsRating({
    emotionSize: 80,
    bgEmotion: 'happy',
    emotions: emotionsArray,
    color: 'gold'
  });

  function test(){
      alert("asd");
  }
</script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>